# Generated by Django 5.0.2 on 2024-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cpu', models.FloatField()),
                ('real_memory', models.FloatField()),
                ('virtual_memory', models.FloatField()),
                ('disck_space', models.FloatField()),
            ],
        ),
    ]
